import type { PlatformDefinition } from '../types.js';

export const blackboard = {
  id: 'blackboard' as const,
  label: 'Blackboard',
  environmentPrefixes: ['BLACKBOARD_'],
  readTools: [
    'bb_whoami',
    'bb_session_status',
    'bb_list_courses',
    'bb_get_course',
    'bb_list_terms',
    'bb_list_roster',
    'bb_browse_course',
    'bb_list_content',
    'bb_get_content',
    'bb_search_content',
    'bb_list_grades',
    'bb_get_grade_detail',
    'bb_grade_summary',
    'bb_review_quiz_attempt',
    'bb_submission_status',
    'bb_list_files',
    'bb_read_file',
    'bb_todo',
    'bb_calendar',
    'bb_course_schedule',
    'bb_announcements',
    'bb_activity_stream',
    'bb_list_conversations',
    'bb_list_discussions',
    'bb_attendance',
    'bb_unread_counts',
  ],
  aliases: {
    courses: 'bb_list_courses',
    announcements: 'bb_announcements',
    calendar: 'bb_calendar',
    todo: 'bb_todo',
    grades: 'bb_list_grades',
    files: 'bb_list_files',
    content: 'bb_list_content',
    inbox: 'bb_list_conversations',
    profile: 'bb_whoami',
    activity: 'bb_activity_stream',
  },
  courseArgument: { name: 'courseId', type: 'string' },
  login: {
    cookieNames: /^(BbRouter|JSESSIONID|xsrf|AWSELB[A-Za-z0-9_-]*|BbAuth[A-Za-z0-9_-]*|s_session_id|session_id)$/,
    sessionCookieNames: ['BbRouter', 'JSESSIONID'],
    probePath: '/learn/api/v1/users/me',
  },
  probes: { identity: { tool: 'bb_whoami' }, courses: { tool: 'bb_list_courses' } },
  overview: ({ days }) => ({
    calls: [
      { tool: 'bb_list_courses' },
      { tool: 'bb_announcements', args: { limit: 20, fullText: true, maxCourses: 15 } },
      { tool: 'bb_todo', args: { days } },
      { tool: 'bb_calendar', args: { days } },
    ],
    scope: { announcementsPerCourse: 20, maxCourses: 15, attachmentsRead: false },
    legacyScope: { blackboardAnnouncementsPerCourse: 20, blackboardMaxCourses: 15 },
  }),
  limitations: 'Blackboard depends on Learn Ultra internal APIs, which may vary or change between institutions and versions.',
  loadRuntime: async () => (await import('./runtime.js')).runtime,
} satisfies PlatformDefinition;
