import type { PlatformDefinition } from '../types.js';

export const canvas = {
  id: 'canvas' as const,
  label: 'Canvas',
  environmentPrefixes: ['CANVAS_'],
  readTools: [
    'canvas_get_profile',
    'canvas_list_courses',
    'canvas_get_course',
    'canvas_list_assignments',
    'canvas_get_assignment',
    'canvas_get_grades',
    'canvas_list_announcements',
    'canvas_list_modules',
    'canvas_list_pages',
    'canvas_get_page',
    'canvas_list_files',
    'canvas_get_file_link',
    'canvas_list_discussions',
    'canvas_get_discussion',
    'canvas_list_quizzes',
    'canvas_list_todo',
    'canvas_list_upcoming',
    'canvas_list_calendar_events',
    'canvas_list_inbox',
    'canvas_get_conversation',
    'canvas_get_feedback',
    'canvas_grade_breakdown',
    'canvas_list_planner',
    'canvas_read_file',
    'canvas_read_syllabus',
    'canvas_list_groups',
    'canvas_get_module_progress',
    'canvas_list_peer_reviews',
    'canvas_export_course',
  ],
  aliases: {
    courses: 'canvas_list_courses',
    announcements: 'canvas_list_announcements',
    assignments: 'canvas_list_assignments',
    calendar: 'canvas_list_calendar_events',
    todo: 'canvas_list_todo',
    grades: 'canvas_get_grades',
    files: 'canvas_list_files',
    pages: 'canvas_list_pages',
    modules: 'canvas_list_modules',
    inbox: 'canvas_list_inbox',
    profile: 'canvas_get_profile',
  },
  courseArgument: { name: 'course_id', type: 'number' },
  login: {
    cookieNames: /^(canvas_session|_csrf_token|_normandy_session|log_session_id)$/,
    sessionCookieNames: ['canvas_session'],
    probePath: '/api/v1/users/self/profile',
  },
  probes: { identity: { tool: 'canvas_get_profile' }, courses: { tool: 'canvas_list_courses' } },
  overview: ({ days, now }) => {
    const date = (offset: number) => new Date(now.getTime() + offset * 86400_000).toISOString().slice(0, 10);
    return {
      calls: [
        { tool: 'canvas_list_courses' },
        { tool: 'canvas_list_announcements', args: { start_date: date(-90), max_chars: 20000 } },
        { tool: 'canvas_list_planner', args: { days_ahead: days, days_back: 0 } },
        { tool: 'canvas_list_calendar_events', args: { start_date: date(0), end_date: date(days) } },
      ],
      scope: { announcementLookbackDays: 90, announcementMaxChars: 20000, attachmentsRead: false },
      legacyScope: { canvasAnnouncementLookbackDays: 90 },
    };
  },
  limitations: 'Canvas REST access depends on the institution and account permissions; identity/course checks do not verify all tools.',
  loadRuntime: async () => (await import('./runtime.js')).runtime,
} satisfies PlatformDefinition;
